import { useState } from 'react';
import Sidebar from './components/Sidebar';
import MainPost from './components/MainPost';
import './App.css';

function App() {
  
	const DATA = [
		{title: 'Blog Post 1', body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fugit dicta soluta optio tempore iusto ab consequuntur obcaecati repellat! Veniam, expedita beatae neque recusandae pariatur quidem sit quod! Voluptatum, libero cumque? Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum quidem tempora neque officiis beatae iste nesciunt delectus et similique. Ipsa magni placeat quae vitae eius, ipsum quas fugit distinctio nulla. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, delectus fuga rerum inventore ipsam sit soluta officia in adipisci sequi ex quasi natus impedit. Consectetur, assumenda sit? Quae, voluptate laboriosam.'},
		{title: 'Blog Post 2', body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta fuga nostrum nobis deleniti, modi commodi rerum soluta hic voluptates explicabo, officia a molestias sed error beatae voluptate nemo animi quo?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Expedita aliquid nesciunt deleniti reprehenderit alias rerum, officia ratione voluptas, maiores dolorum doloribus facere molestiae fuga atque ut. Debitis totam quidem laborum lorem laborum lorem'},
		{title: 'Blog Post 3', body: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Adipisci commodi quas nulla obcaecati earum excepturi explicabo ipsam rerum, omnis sit fugiat debitis accusamus odio tenetur cumque recusandae? Aliquam, tempore cum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus quam praesentium animi facilis, aliquam numquam qui accusamus eos? Fuga quidem voluptatibus quae dolorem sint, perferendis iure ipsam sit exercitationem provident. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero officia voluptates quis saepe ex quos tenetur dolores maxime dolorum ipsam. Debitis officiis corrupti fuga nulla, quae doloremque ut numquam? Quis!'},
		{title: 'Blog Post 4', body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero non esse a, molestias ut quasi autem delectus sapiente culpa dignissimos architecto expedita placeat nam cum labore nulla. Saepe, hic aperiam! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos harum vel voluptate, alias, quae deleniti omnis deserunt aperiam perspiciatis commodi fuga et architecto? Odit molestiae beatae nisi laudantium sunt minus. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cumque aut animi ducimus sed vitae adipisci vel a dolore exercitationem recusandae odio quaerat placeat tenetur, tempore nisi sequi ipsum officia aspernatur.'},
		{title: 'Blog Post 5', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro autem, eligendi, similique praesentium tempora suscipit et natus quam omnis quia fuga eius voluptate voluptates hic eveniet quod vero illum dolorem! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex aut velit, iure ipsa corporis voluptatem eius aspernatur, dignissimos veniam tempore minima sed architecto voluptas! Et culpa tempora quas amet commodi! lorem 	'},
		{title: 'Blog Post 6', body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque ex quasi accusantium porro consequatur aut quos debitis fuga cupiditate? Corporis accusantium, odit officia assumenda eos quod aliquid amet error alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium, expedita ex! Repellat molestias tenetur cupiditate fugiat deserunt incidunt totam sequi. Ipsum obcaecati soluta id dolore, cum eum quo voluptates porro? Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque exercitationem accusantium optio minus ratione, eligendi dolorum quos, cumque provident repellat blanditiis. Illum officia sunt eum neque similique ea distinctio tempore.'},
		{title: 'Blog Post 7', body: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem sapiente accusantium veniam doloribus dolores, quis libero temporibus ut ipsa consequuntur sequi! Dicta consequatur maiores cumque id corporis optio deserunt ut. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi beatae praesentium minima deserunt perspiciatis rerum a quaerat ipsum, et dolorem suscipit magni consequuntur nam adipisci asperiores quibusdam, aliquid, facilis perferendis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis rem distinctio autem, voluptates vitae quaerat possimus praesentium unde sit ullam sapiente porro totam et eum voluptas libero eligendi dolor maiores?'},
		{title: 'Blog Post 8', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro autem, eligendi, similique praesentium tempora suscipit et natus quam omnis quia fuga eius voluptate voluptates hic eveniet quod vero illum dolorem! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex aut velit, iure ipsa corporis voluptatem eius aspernatur, dignissimos veniam tempore minima sed architecto voluptas! Et culpa tempora quas amet commodi! lorem 	'},
		{title: 'Blog Post 9', body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque ex quasi accusantium porro consequatur aut quos debitis fuga cupiditate? Corporis accusantium, odit officia assumenda eos quod aliquid amet error alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium, expedita ex! Repellat molestias tenetur cupiditate fugiat deserunt incidunt totam sequi. Ipsum obcaecati soluta id dolore, cum eum quo voluptates porro? Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque exercitationem accusantium optio minus ratione, eligendi dolorum quos, cumque provident repellat blanditiis. Illum officia sunt eum neque similique ea distinctio tempore.'},
		{title: 'Blog Post 10', body: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem sapiente accusantium veniam doloribus dolores, quis libero temporibus ut ipsa consequuntur sequi! Dicta consequatur maiores cumque id corporis optio deserunt ut. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi beatae praesentium minima deserunt perspiciatis rerum a quaerat ipsum, et dolorem suscipit magni consequuntur nam adipisci asperiores quibusdam, aliquid, facilis perferendis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis rem distinctio autem, voluptates vitae quaerat possimus praesentium unde sit ullam sapiente porro totam et eum voluptas libero eligendi dolor maiores?'},
		{title: 'Blog Post 11', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro autem, eligendi, similique praesentium tempora suscipit et natus quam omnis quia fuga eius voluptate voluptates hic eveniet quod vero illum dolorem! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex aut velit, iure ipsa corporis voluptatem eius aspernatur, dignissimos veniam tempore minima sed architecto voluptas! Et culpa tempora quas amet commodi! lorem 	'},
		{title: 'Blog Post 12', body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque ex quasi accusantium porro consequatur aut quos debitis fuga cupiditate? Corporis accusantium, odit officia assumenda eos quod aliquid amet error alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium, expedita ex! Repellat molestias tenetur cupiditate fugiat deserunt incidunt totam sequi. Ipsum obcaecati soluta id dolore, cum eum quo voluptates porro? Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque exercitationem accusantium optio minus ratione, eligendi dolorum quos, cumque provident repellat blanditiis. Illum officia sunt eum neque similique ea distinctio tempore.'},
		{title: 'Blog Post 13', body: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem sapiente accusantium veniam doloribus dolores, quis libero temporibus ut ipsa consequuntur sequi! Dicta consequatur maiores cumque id corporis optio deserunt ut. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi beatae praesentium minima deserunt perspiciatis rerum a quaerat ipsum, et dolorem suscipit magni consequuntur nam adipisci asperiores quibusdam, aliquid, facilis perferendis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis rem distinctio autem, voluptates vitae quaerat possimus praesentium unde sit ullam sapiente porro totam et eum voluptas libero eligendi dolor maiores?'},
		{title: 'Blog Post 14', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro autem, eligendi, similique praesentium tempora suscipit et natus quam omnis quia fuga eius voluptate voluptates hic eveniet quod vero illum dolorem! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex aut velit, iure ipsa corporis voluptatem eius aspernatur, dignissimos veniam tempore minima sed architecto voluptas! Et culpa tempora quas amet commodi! lorem 	'},
		{title: 'Blog Post 15', body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque ex quasi accusantium porro consequatur aut quos debitis fuga cupiditate? Corporis accusantium, odit officia assumenda eos quod aliquid amet error alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium, expedita ex! Repellat molestias tenetur cupiditate fugiat deserunt incidunt totam sequi. Ipsum obcaecati soluta id dolore, cum eum quo voluptates porro? Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque exercitationem accusantium optio minus ratione, eligendi dolorum quos, cumque provident repellat blanditiis. Illum officia sunt eum neque similique ea distinctio tempore.'}
	]

	const [selection, setSelection] = useState(DATA[0]);

	const selectPost = newPost => {
		setSelection(newPost);
	}
  
  	return (
    	<div className="App">
			<Sidebar data={DATA} selectPost={selectPost}/>
			<MainPost {...selection}/>
    	</div>
  	);
}

export default App;