import { useState } from 'react';
import Sidebar from './components/Sidebar';
import MainPost from './components/MainPost';
import './App.css';

function App() {
  
	const DATA = [
		{title: 'Blog Post 1', body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fugit dicta soluta optio tempore iusto ab consequuntur obcaecati repellat! Veniam, expedita beatae neque recusandae pariatur quidem sit quod! Voluptatum, libero cumque? Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum quidem tempora neque officiis beatae iste nesciunt delectus et similique. Ipsa magni placeat quae vitae eius, ipsum quas fugit distinctio nulla. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, delectus fuga rerum inventore ipsam sit soluta officia in adipisci sequi ex quasi natus impedit. Consectetur, assumenda sit? Quae, voluptate laboriosam.'},
		{title: 'Blog Post 2', body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fugit dicta soluta optio tempore iusto ab consequuntur obcaecati repellat! Veniam, expedita beatae neque recusandae pariatur quidem sit quod! Voluptatum, libero cumque? Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum quidem tempora neque officiis beatae iste nesciunt delectus et similique. Ipsa magni placeat quae vitae eius, ipsum quas fugit distinctio nulla. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, delectus fuga rerum inventore ipsam sit soluta officia in adipisci sequi ex quasi natus impedit. Consectetur, assumenda sit? Quae, voluptate laboriosam.'},
		{title: 'Blog Post 3', body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fugit dicta soluta optio tempore iusto ab consequuntur obcaecati repellat! Veniam, expedita beatae neque recusandae pariatur quidem sit quod! Voluptatum, libero cumque? Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum quidem tempora neque officiis beatae iste nesciunt delectus et similique. Ipsa magni placeat quae vitae eius, ipsum quas fugit distinctio nulla. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, delectus fuga rerum inventore ipsam sit soluta officia in adipisci sequi ex quasi natus impedit. Consectetur, assumenda sit? Quae, voluptate laboriosam.'},
		{title: 'Blog Post 4', body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fugit dicta soluta optio tempore iusto ab consequuntur obcaecati repellat! Veniam, expedita beatae neque recusandae pariatur quidem sit quod! Voluptatum, libero cumque? Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum quidem tempora neque officiis beatae iste nesciunt delectus et similique. Ipsa magni placeat quae vitae eius, ipsum quas fugit distinctio nulla. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, delectus fuga rerum inventore ipsam sit soluta officia in adipisci sequi ex quasi natus impedit. Consectetur, assumenda sit? Quae, voluptate laboriosam.'},
		{title: 'Blog Post 5', body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fugit dicta soluta optio tempore iusto ab consequuntur obcaecati repellat! Veniam, expedita beatae neque recusandae pariatur quidem sit quod! Voluptatum, libero cumque? Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum quidem tempora neque officiis beatae iste nesciunt delectus et similique. Ipsa magni placeat quae vitae eius, ipsum quas fugit distinctio nulla. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, delectus fuga rerum inventore ipsam sit soluta officia in adipisci sequi ex quasi natus impedit. Consectetur, assumenda sit? Quae, voluptate laboriosam.'},
		{title: 'Blog Post 6', body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fugit dicta soluta optio tempore iusto ab consequuntur obcaecati repellat! Veniam, expedita beatae neque recusandae pariatur quidem sit quod! Voluptatum, libero cumque? Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum quidem tempora neque officiis beatae iste nesciunt delectus et similique. Ipsa magni placeat quae vitae eius, ipsum quas fugit distinctio nulla. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, delectus fuga rerum inventore ipsam sit soluta officia in adipisci sequi ex quasi natus impedit. Consectetur, assumenda sit? Quae, voluptate laboriosam.'},
		{title: 'Blog Post 7', body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fugit dicta soluta optio tempore iusto ab consequuntur obcaecati repellat! Veniam, expedita beatae neque recusandae pariatur quidem sit quod! Voluptatum, libero cumque? Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum quidem tempora neque officiis beatae iste nesciunt delectus et similique. Ipsa magni placeat quae vitae eius, ipsum quas fugit distinctio nulla. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, delectus fuga rerum inventore ipsam sit soluta officia in adipisci sequi ex quasi natus impedit. Consectetur, assumenda sit? Quae, voluptate laboriosam.'},
		{title: 'Blog Post 8', body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fugit dicta soluta optio tempore iusto ab consequuntur obcaecati repellat! Veniam, expedita beatae neque recusandae pariatur quidem sit quod! Voluptatum, libero cumque? Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum quidem tempora neque officiis beatae iste nesciunt delectus et similique. Ipsa magni placeat quae vitae eius, ipsum quas fugit distinctio nulla. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, delectus fuga rerum inventore ipsam sit soluta officia in adipisci sequi ex quasi natus impedit. Consectetur, assumenda sit? Quae, voluptate laboriosam.'},
		{title: 'Blog Post 9', body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fugit dicta soluta optio tempore iusto ab consequuntur obcaecati repellat! Veniam, expedita beatae neque recusandae pariatur quidem sit quod! Voluptatum, libero cumque? Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum quidem tempora neque officiis beatae iste nesciunt delectus et similique. Ipsa magni placeat quae vitae eius, ipsum quas fugit distinctio nulla. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, delectus fuga rerum inventore ipsam sit soluta officia in adipisci sequi ex quasi natus impedit. Consectetur, assumenda sit? Quae, voluptate laboriosam.'},
		{title: 'Blog Post 10', body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fugit dicta soluta optio tempore iusto ab consequuntur obcaecati repellat! Veniam, expedita beatae neque recusandae pariatur quidem sit quod! Voluptatum, libero cumque? Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum quidem tempora neque officiis beatae iste nesciunt delectus et similique. Ipsa magni placeat quae vitae eius, ipsum quas fugit distinctio nulla. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, delectus fuga rerum inventore ipsam sit soluta officia in adipisci sequi ex quasi natus impedit. Consectetur, assumenda sit? Quae, voluptate laboriosam.'},
		{title: 'Blog Post 11', body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fugit dicta soluta optio tempore iusto ab consequuntur obcaecati repellat! Veniam, expedita beatae neque recusandae pariatur quidem sit quod! Voluptatum, libero cumque? Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum quidem tempora neque officiis beatae iste nesciunt delectus et similique. Ipsa magni placeat quae vitae eius, ipsum quas fugit distinctio nulla. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, delectus fuga rerum inventore ipsam sit soluta officia in adipisci sequi ex quasi natus impedit. Consectetur, assumenda sit? Quae, voluptate laboriosam.'},
		{title: 'Blog Post 12', body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fugit dicta soluta optio tempore iusto ab consequuntur obcaecati repellat! Veniam, expedita beatae neque recusandae pariatur quidem sit quod! Voluptatum, libero cumque? Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum quidem tempora neque officiis beatae iste nesciunt delectus et similique. Ipsa magni placeat quae vitae eius, ipsum quas fugit distinctio nulla. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, delectus fuga rerum inventore ipsam sit soluta officia in adipisci sequi ex quasi natus impedit. Consectetur, assumenda sit? Quae, voluptate laboriosam.'},
		{title: 'Blog Post 13', body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fugit dicta soluta optio tempore iusto ab consequuntur obcaecati repellat! Veniam, expedita beatae neque recusandae pariatur quidem sit quod! Voluptatum, libero cumque? Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum quidem tempora neque officiis beatae iste nesciunt delectus et similique. Ipsa magni placeat quae vitae eius, ipsum quas fugit distinctio nulla. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, delectus fuga rerum inventore ipsam sit soluta officia in adipisci sequi ex quasi natus impedit. Consectetur, assumenda sit? Quae, voluptate laboriosam.'},
		{title: 'Blog Post 14', body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fugit dicta soluta optio tempore iusto ab consequuntur obcaecati repellat! Veniam, expedita beatae neque recusandae pariatur quidem sit quod! Voluptatum, libero cumque? Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum quidem tempora neque officiis beatae iste nesciunt delectus et similique. Ipsa magni placeat quae vitae eius, ipsum quas fugit distinctio nulla. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, delectus fuga rerum inventore ipsam sit soluta officia in adipisci sequi ex quasi natus impedit. Consectetur, assumenda sit? Quae, voluptate laboriosam.'},
		{title: 'Blog Post 15', body: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fugit dicta soluta optio tempore iusto ab consequuntur obcaecati repellat! Veniam, expedita beatae neque recusandae pariatur quidem sit quod! Voluptatum, libero cumque? Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum quidem tempora neque officiis beatae iste nesciunt delectus et similique. Ipsa magni placeat quae vitae eius, ipsum quas fugit distinctio nulla. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, delectus fuga rerum inventore ipsam sit soluta officia in adipisci sequi ex quasi natus impedit. Consectetur, assumenda sit? Quae, voluptate laboriosam.'}
	]

	const [selection, setSelection] = useState(DATA[0]);

	const selectPost = newPost => {
		setSelection(newPost);
	}
  
  	return (
    	<div className="App">
			<Sidebar data={DATA} selectPost={selectPost}/>
			<MainPost {...selection}/>
    	</div>
  	);
}

export default App;